server_addr: 127.0.0.1
# server_addr is the IP/hostname of the HTTP server running nephology
# mirror_addr is the IP/hostname of an HTTP server with an ubuntu mirror
mirror_addr: 127.0.0.1
pub_ssh_key_file: /etc/nephology/nephology.ssh.pub
db_name: nephology2
db_username: nephology
db_password: 
db_type: mysql
db_host: localhost
discovery: enable
default_domain: local.domain
default_node_status: 1000
